FROM maven:3.8-openjdk-17-slim AS build
ARG SERVICE_NAME
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl ${SERVICE_NAME} -am -B

FROM openjdk:17-jre-slim
ARG SERVICE_NAME
WORKDIR /app
COPY --from=build /app/${SERVICE_NAME}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Xms256m", "-Xmx512m", "app.jar"]
