server:
  port: 8086

aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:}
    bucket: ${ALIYUN_OSS_BUCKET:}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    cdn-domain: ${ALIYUN_OSS_CDN_DOMAIN:}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/botmedia_media?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
