server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/botmedia_payment?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

wechat:
  pay:
    mch-id: ${WECHAT_PAY_MCH_ID:}
    api-key: ${WECHAT_PAY_API_KEY:}
    cert-path: ${WECHAT_PAY_CERT_PATH:}
    notify-url: ${WECHAT_PAY_NOTIFY_URL:}
